Add phasor dynamics bus and branch models
ORNL/GridKit pull request #38
Opened 2024-12-23 22:15 UTC by pelesh

Models for a bus and a branch for phasor dynamics simulations are added. These models use current balance and Cartesian coordinates.

2025-01-10 14:59 UTC, abirchfield requested changes

2025-01-10 14:59 UTC, abirchfield commented on ComponentLib/PhasorDynamics/Bus/Bus.hpp
> +        ScalarT Va0_{0.0};
This should be Vr0 and Vi0, along with the constructor.

2025-01-10 14:59 UTC, abirchfield commented on ComponentLib/PhasorDynamics/Bus/Bus.hpp
> +        Bus(ScalarT Va, ScalarT Vr);
Vr, Vi

2025-01-10 14:59 UTC, abirchfield commented on ComponentLib/PhasorDynamics/Bus/Bus.cpp
> +  : Va0_(0.0), Vr0_(0.0)
Vr,Vi

2025-01-10 14:59 UTC, abirchfield commented on ComponentLib/PhasorDynamics/Bus/Bus.cpp
> +  : Va0_(Va), Vr0_(Vr)
Vr,Vi

2025-01-10 14:59 UTC, abirchfield commented on ComponentLib/PhasorDynamics/Bus/Bus.cpp
> +  : Va0_(data.Vm * cos(data.Va)), Vr0_(data.Vm * sin(data.Va))
Vr,Vi

2025-01-10 14:59 UTC, abirchfield commented on ComponentLib/PhasorDynamics/Bus/README.md
> +variables -- active and reactive voltage $`V_{ai}`$ and $`V_{ri}`$,
The terms "active and reactive voltage" have no physical meaning. We should say "real and imaginary components of the voltage phasor". Same thing with current. On the other hand, active and reactive power are OK to talk about.

2025-01-13 21:14 UTC, pelesh commented on ComponentLib/PhasorDynamics/Bus/Bus.hpp
> +        Bus(ScalarT Va, ScalarT Vr);
Fixed in [c79256c](https://github.com/ORNL/GridKit/pull/38/commits/c79256c777476a95e9ea21c194de40f829184c09).

2025-01-13 21:14 UTC, pelesh commented on ComponentLib/PhasorDynamics/Bus/Bus.cpp
> +  : Va0_(0.0), Vr0_(0.0)
Fixed in [c79256c](https://github.com/ORNL/GridKit/pull/38/commits/c79256c777476a95e9ea21c194de40f829184c09).

2025-01-13 21:14 UTC, pelesh commented on ComponentLib/PhasorDynamics/Bus/Bus.cpp
> +  : Va0_(Va), Vr0_(Vr)
Fixed in [c79256c](https://github.com/ORNL/GridKit/pull/38/commits/c79256c777476a95e9ea21c194de40f829184c09).

2025-01-13 21:14 UTC, pelesh commented on ComponentLib/PhasorDynamics/Bus/README.md
> +variables -- active and reactive voltage $`V_{ai}`$ and $`V_{ri}`$,
Fixed in [c79256c](https://github.com/ORNL/GridKit/pull/38/commits/c79256c777476a95e9ea21c194de40f829184c09).

2025-01-21 20:44 UTC, abirchfield approved these changes
Everything looks good to me.

2025-01-21 21:03 UTC, merged